### ISSUE TITLE
Incorrect Recurrence Rule creation with YEARLY frequency and BYMONTH 

### ISSUE THREAD

**Issue by nicoladj77** [iCalcreator/iCalcreator#10]
I've got an event which starts on the 30th of october 2014 at 5.30 PM. I'm using `iCalUtilityFunctions::_recur2date` to calculate recurrence rules. 

I've got the following:

``` php

$recurrence_rules = array(
  ['FREQ'] =>
  'YEARLY',
  ['BYMONTH'] =>
  11,
);

$startdate = $wdate = array(
  ['year'] =>
  2014,
  ['month'] =>
  11,
  ['day'] =>
  30,
  ['hour'] =>
  17,
  ['min'] =>
  30,
  ['sec'] =>
  00,
  ['tz'] =>
  'Z',
);

$enddate = array(
  ['year'] =>
  2017,
  ['month'] =>
  11,
  ['day'] =>
  30,
  ['hour'] =>
  17,
  ['min'] =>
  30,
  ['sec'] =>
  00,
  ['tz'] =>
  'Z',
);

iCalUtilityFunctions::_recur2date(
    $recurrence_dates,
    $recurrence_rules,
    $wdate,
    $startdate,
    $enddate
);

/*
$recurrence_dates is equal to:

array(
  [1446481800] => TRUE, // this is  2015 11 02
  [1478104200] => TRUE, // this is  2016 11 02
  [1509640200] => TRUE, // this is  2017 11 02
)
*/

```

as you can see the recurrence array is wrong, because since no BYDAY is used the start date should be use as the recurrence date. This happens also if the startdate is the 29th of november but not on the 28th which works as expected

**Comment by iCalcreator** [comment]
Fixed in the 2.22 release.
Note, fcns selectComponents and _recur2date are reworked in this release
and _recur2date has a changed return format.
