### ISSUE TITLE
Parsing fails when TZID is a windows timezone string

### ISSUE THREAD

**Issue by cgoIT** [iCalcreator/iCalcreator#102]
Hi,

first of all I have to say that I'm not a iCal RFC expert. So I don't know if the RFC forbids to use microsoft windows timezone strings for the TZID field. If so, it could be discussed if this is really an error.

I tried to parse the following iCal file:

```
BEGIN:VCALENDAR
PRODID:-//davical.org//NONSGML AWL Calendar//EN
VERSION:2.0
CALSCALE:GREGORIAN
BEGIN:VEVENT
CREATED:20220722T060139Z
DTEND;VALUE=DATE:20220825
DTSTAMP:20220722T060142Z
DTSTART;VALUE=DATE:20220714
LAST-MODIFIED:20220722T060139Z
SEQUENCE:0
SUMMARY:Sommerferien
TRANSP:OPAQUE
UID:9CF2B5AE-294E-4103-A2AE-5A4F027494D9
END:VEVENT
BEGIN:VEVENT
CLASS:PUBLIC
DTEND;TZID=W. Europe Standard Time:20200306T140000
DTSTAMP:20200416T150258Z
DTSTART;TZID=W. Europe Standard Time:20200305T090000
LOCATION:Walsrode
PRIORITY:5
SEQUENCE:0
SUMMARY:PiC abwesend Workshop QSL
TRANSP:OPAQUE
UID:34af6777-8de1-406d-bf94-a38d3b7d6ae7
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
END:VEVENT
```

As you can see the timezone used is qualified via a microsoft windows timezone string "W. Europe Standard Time". This will prevent the parsing of the iCal file.

I will provide a PR that tries to determine the IANA timezone out of the microsoft windows timezone that will fix this error.

**Comment by iCalcreator** [comment]
The RFC "does not define a naming convention for time zone identifiers",
but iCalcreator internally use DateTime for Dt-properties, RDATE, RRULE, FREEBUSY, TZID etc
and must have a PHP valid timezone.
So, nice PR, but have to examine all input timezone usage, update code, review and extend the tests
before a new release.

**Comment by iCalcreator** [comment]
Please test the new 2.41.57 release !

**Comment by cgoIT** [comment]
Hi, I‘m on vacation right now. Will test it next week.

**Comment by cgoIT** [comment]
Hi,
I can confirm that it's working with the latest release. Thx a lot!!

**Comment by iCalcreator** [comment]
Thanks for the issue and for the PR!
