### ISSUE TITLE
Leading semicolon in RRULE

### ISSUE THREAD

**Issue by egst** [iCalcreator/iCalcreator#105]
The iCalendar standard ([recurrence rule](https://icalendar.org/iCalendar-RFC-5545/3-3-10-recurrence-rule.html), [recurrence rule definition](https://icalendar.org/iCalendar-RFC-5545/3-8-5-3-recurrence-rule.html)) defines the RRULE property definition syntax as follows (simplified):

```
rrule = "RRULE" ":" recur-rule-part *( ";" recur-rule-part )
recur-rule-part = ( "FREQ" "=" freq ) / ( "UNTIL" "=" enddate ) / ...
```

There should be no semicolon at the beginning before the first `recur-rule-part`, however, iCalcreator generates it:

```
RRULE:;FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
```

There used to be a [check](https://github.com/iCalcreator/iCalcreator/compare/v2.41.67...v2.41.70#diff-efe1e4f432d6106bc8253cef2f4c9d7ec1c9e8a6aa6ab57209f30d5b6e6833c7L91) specifically for FREQ, that would only add the leading semicolon if it's not the first rule in the list. (I'm not sure why it's only for FREQ.) In [v2.41.70](https://github.com/iCalcreator/iCalcreator/releases/tag/v2.41.70), this was changed and now for all rules added, a semicolon is prepended in the [renderString](https://github.com/iCalcreator/iCalcreator/blob/29de07fd6954653f3ac2117ce37555ecb1abbc67/src/Formatter/Property/Recur.php#L118) method.

It seems like the applications I've tried recognize the RRULE anyway, so it's probably not an issue. Could you please confirm, that this is in fact OK to use in practice despite not being strictly standard? If not, I'd gladly help with implementing a fix.

**Comment by iCalcreator** [comment]
Yes, it's a bug, will fix it asap !

28 november 2022 10:51:04 +01:00, skrev Maximilian Kulikov ***@***.***>:

**Comment by egst** [comment]
Thanks!
