### ISSUE TITLE
The isUTCtimeZone method does not work properly all the time

### ISSUE THREAD

**Issue by chosten** [iCalcreator/iCalcreator#106]
If you generate a calendar (during winter time) with an event starting 2023-04-20 10:00 with the timezone Europe/London and then imports it into outlook the time of the event is offseted by an hour.

I believe this is because the VTIMEZONE component does not include the STANDARD and DAYLIGHT properties. And it does not include them because of a bug in the `isUTCtimeZone` method when it is called from `processSingleTimezone`.
The value returned by `DateTimeZone->getOffset` is wrong because it uses the current date (winter time) instead of the date of the event (summer time). In my example it should return 3600 instead of 0.

**Comment by iCalcreator** [comment]
Now in the top of the todo-list

**Comment by iCalcreator** [comment]
New release 2.42.74, please test

**Comment by henrikthorn** [comment]
We experience a similar error, but only in Outlook. And only in the app and not the web-version. We've narrowed it down to Outlook not reading the RDATE correctly. 

This is what is generated, which does not work with Outlook. 

```
BEGIN:VTIMEZONE
TZID:Europe/Copenhagen
TZUNTIL:20241027T010000Z
BEGIN:STANDARD
TZNAME:CET
DTSTART:20221030T030000
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
RDATE:20231029T030000
END:STANDARD
BEGIN:DAYLIGHT
TZNAME:CEST
DTSTART:20220327T020000
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
RDATE:20230326T020000
RDATE:20240331T020000
END:DAYLIGHT
END:VTIMEZONE
```

We've gotten this to work:

```
BEGIN:VTIMEZONE
TZID:Europe/Copenhagen
TZUNTIL:20241027T010000Z
BEGIN:STANDARD
TZNAME:CET
DTSTART:20221030T030000
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
BEGIN:DAYLIGHT
TZNAME:CEST
DTSTART:20220327T020000
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
END:VTIMEZONE
```

**Comment by chosten** [comment]
I did some tests again. The isUTCtimeZone bug seems fixed to me.

**Comment by iCalcreator** [comment]
It seems to be an Outlook 'feature' here, not an error in iCalcreator.
