### ISSUE TITLE
Low strict mode

### ISSUE THREAD

**Issue by maieul** [iCalcreator/iCalcreator#112]
Hi,

using ical creator v2.41.56

in the handbook, it is said

> Minor errors like non-standard line-endings, initial and trailing empty lines as well as files without proper end line(-s) (i.e. missing component end and/or "END:CALENDAR" iCal directives) are managed.

However,
https://www.cineclubfrancoistruffaut.fr/?page=agenda-ical
as an empty line at l.24 after `SEQUENCE:1`

And I got a type error, because the library expect sequence to be a int, and get `'1 '` (maybe I trim could be done). 

Another error, from another feed is when the ORGANIZER contain URL and not mail

`
ORGANIZER;CN="Paroisse : église de Jonquières (Saint Mapalice)":http://messes.info/communaute/av/84/jonquieres
`

That made a

`
Fatal error: Uncaught InvalidArgumentException: Invalid email mailto:http://messes.info/communaute/av/84/jonquieres in C:\laragon\_spipmu4_\plugins\_plugin_spipmu_prod_\plugins\icalendar\vendor\kigkonsult\icalcreator\src\Util\CalAddressFactory.php on line *84*
( ! ) InvalidArgumentException: Invalid email mailto:http://messes.info/communaute/av/84/jonquieres in C:\laragon\_spipmu4_\plugins\_plugin_spipmu_prod_\plugins\icalendar\vendor\kigkonsult\icalcreator\src\Util\CalAddressFactory.php on line *84*
Call Stack`

SHould it be possible to have a less strict mode ?

**Comment by iCalcreator** [comment]
Fixed, please try the new 2.41.80 release !

**Comment by maieul** [comment]
Sorry, I was in holiday. But now, I can confirm it work. Thank a lot.
