### ISSUE TITLE
When importing from a Mac calendar, new lines are imported as \n

### ISSUE THREAD

**Issue by nicoladj77** [iCalcreator/iCalcreator#13]
I don't know if this is a bug or not, but when importing location from this calendar webcal://p04-calendars.icloud.com/published/2/B0QN3CyKOgSVIcHmoSD5ue94TfkxdNognNZeM4ML05N7g9jqcshJjT_h0RrrwKSHfMi2jAlAvhmU3mScFjhRJGsclk7jkYvLpw2pa52hWoI new lines are imported as \n. 
Here is the issue on [our forums](https://time.ly/forums/topic/shortcode-erroring/#post-234751)
Looking at your code it seems to try to handle it, but this case fails. Do we need to configure the importer somehow?

**Comment by iCalcreator** [comment]
I'll look into the issue!
