### ISSUE TITLE
Setting filename without directory stop propagation of config setting

### ISSUE THREAD

**Issue by hypeJunction** [iCalcreator/iCalcreator#14]
The logic for setting 'FILENAME' in setConfig is flawed. Iteration through constructor config values does not complete, since filename set for download is not an existing file on the server. As a result you loose config values, including ->nl.

**Comment by iCalcreator** [comment]
Not fixed in the 2.22 release.
A strong recommendation is to set directory/filename using fcn setConfig and validate result.
