### ISSUE TITLE
Parsing of line breaks

### ISSUE THREAD

**Issue by real-or-random** [iCalcreator/iCalcreator#16]
When parsing fields that contain line breaks, I get a literal '\n' (BACKSLASH and N) instead of a newline character.

The issue seems here:
https://github.com/iCalcreator/iCalcreator/blob/master/lib/iCalUtilityFunctions.class.php#L2395

This line is commented. Is there a reason?

Note that ``$nl`` is not defined in the function. I think it would be better to return just a newline character ("\n") consistently on every system. 
So ``$string = str_replace( '\n',  "\n", $string);`` works for me.

I could create a PR if the change does not introduce further problems. 

Two additional notes:
 * According to the RFC, we have to replace '\N' as well.
 * Using arrays as arguments for str_replace(), all replacements could be done as one call This is probably faster than calling str_replace() 4 or 5 times.

**Comment by iCalcreator** [comment]
Yes, the reason in stated in the rfc,
      An intentional formatted text line break MUST only be included in
      a "TEXT" property value by representing the line break with the
      character sequence of BACKSLASH, followed by a LATIN SMALL LETTER
      N or a LATIN CAPITAL LETTER N, that is "\n" or "\N".

And the line in question should be removed (next version...).
I'll look over your two notes.

**Comment by real-or-random** [comment]
I don't understand. If the RFC states that a newline is encoded as BACKSLASH N, then we have to apply the reverse transformation when reading the file.

**Comment by iCalcreator** [comment]
As I see it, its also about "separation of concern".

iCalcreator is managing the iCal (calendar) media 
(i.e. keeping BACKSLASH N/n "as is")  and it is the
responsibility of a "Calendar User Agent" (CUA), 
to manage the content of a TEXT property (and the
BACKSLASH N/n) as noted in the rfc.

Btw, looking into the issue, I discovered some possible
parse BACKSLASH N/n anomalies (fixed in next version),
thanks!

**Comment by real-or-random** [comment]
Okay, I see your point. Separation of concern makes indeed sense, in particular, because there are many possible property types.

As it is implemented currently, it creates a case that cannot be handled by the user agent, because  "\\\\" is replaced by "\".
Assume the input file contains "\\n". The library will output "\n". So the user agent cannot distinguish between "\\\\n" and "\n". (I admit that this will not happen often in practice.)
