### ISSUE TITLE
How to create "X-APPLE-STRUCTURED-LOCATION"?

### ISSUE THREAD

**Issue by yannickoo** [iCalcreator/iCalcreator#17]
It seems like `X-APPLE-STRUCTURED-LOCATION` property cannot be set through `setProperty` method. How can I append a location like this to an event?

```
X-APPLE-STRUCTURED-LOCATION;VALUE=URI;X-ADDRESS=Köpenicker Straße 70\\n1
 0179 Berlin;X-APPLE-RADIUS=14130.83822349481;X-TITLE=Title:geo:52.51075
 3,13.419871
```

**Comment by iCalcreator** [comment]
Try this (works on both calendar and component level):
$x->setProperty( 'X-APPLE-STRUCTURED-LOCATION',
                 'geo:52.510753,13.419871',
                  array( 'VALUE'          => 'URI',
                         'X-ADDRESS'      => 'Köpenicker Straße 7010179 Berlin',
                         'X-APPLE-RADIUS' => '14130.83822349481',
                         'X-TITLE'        => 'Title',
                       )
               );

**Comment by yannickoo** [comment]
Cool thank you :)
