### ISSUE TITLE
Parse just a VEVENT?

### ISSUE THREAD

**Issue by grosch** [iCalcreator/iCalcreator#28]
I'm being passed a VEVENT structure without any containing VCALENDAR.  I need to parse that VEVENT block to pull out the LOCATION and X-APPLE-STRUCTURED-LOCATION properties.  If the latter does not exist, I just create it.  If it's does exist, then I need to pull from that the X-TITLE element, compare it to the LOCATION, and if it doesn't exactly match, then nuke the existing X-APPLE-STRUCTURED-LOCATION and create a new one.  

How would I accomplish that?

**Comment by iCalcreator** [comment]
Create a new vcalendar instance
`$c    = new vcalendar( array( 'unique_id' => 'kigkonsult.se' ));`

Create a new vevent component instance
`$e = $c->newComponent( "vevent" );`

Parse a "vevent"-string (rfc5545 format)
`$e->parse( $veventString );`

You can when get and set properties, like
`$location = $e->getProperty( 'location' );`
(false if not found)
`$e->setProperty( 'location', $location );`

You don't need to delete any x-properties 
if you replace it with a 'new' using the same x-name.
