### ISSUE TITLE
selectComponents (with split TRUE) not respecting timezone of ICS

### ISSUE THREAD

**Issue by bclarkau** [iCalcreator/iCalcreator#30]
Hi,

I'm having trouble with my call to selectComponents with the "split" variable set to true. It doesn't seem to take into account the timezone in the ICS when splitting days.

For example:

The Google Calendar I am using to test (see ICS below) has one event that starts at 11/Dec/2016 9am AEDT and ends at 11/Dec/2016 11am AEDT. This gets translated to UTC by Google for the ICS, becoming 10/Dec/2016 10pm UTC and 11/Dec/2016 12am UTC respectively (note that this causes the event to span two days)

> BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:Calendar Test
X-WR-TIMEZONE:Australia/Sydney
X-WR-CALDESC:
BEGIN:VEVENT
DTSTART:20161210T220000Z
DTEND:20161211T000000Z
DTSTAMP:20161212T005722Z
UID:6o5v73597ecnv463ag9jgfoj4k@google.com
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;CN=Calend
 ar Test;X-NUM-GUESTS=0:mailto:be00dpu4toia9vqr7u1dk0ockk@group.calendar.goo
 gle.com
CREATED:20161209T032424Z
DESCRIPTION:Some description\nThis is a new line
LAST-MODIFIED:20161209T034533Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:Test Timezone Overlap
TRANSP:OPAQUE
END:VEVENT
END:VCALENDAR

I am then calling selectComponents like so (split parameter is true):

`$events = $vcalendar->selectComponents( 2016, 12, 1, 2017, 1, 1, "vevent", false, true, true );`

This results in two identical events being returned. Rather than one event (corresponding to the AEDT time) like I would expect. 

Is there a way I can make selectComponents take into account the timezone set in the ICS (X-WR-TIMEZONE) when splitting events? Failing that, perhaps a way I can manually specify which timezone I want events split by?

Or is this not possible at all? 

Thanks!

**Comment by iCalcreator** [comment]
It is a bug, the second event is 'empty', fixed in the coming 2.24 release.

The X-WR-TIMEZONE is a text non-standard (rfc5545) property,
selectComponents uses the DTSTART timezone.

**Comment by iCalcreator** [comment]
Ref 2.23.18
