### ISSUE TITLE
Facebook events feed

### ISSUE THREAD

**Issue by ksartnl** [iCalcreator/iCalcreator#32]
I'm trying to load a ical upcoming Facebook events feed. I use iCalcreator with composer, and this is my PHP file:

```
require_once('vendor/autoload.php'); 
$v = new vcalendar();
$v->setConfig('url', 'http://www.facebook.com/ical/u.php?uid=..&key=..');
$v->parse();
$v->sort();
while( $comp = $v->getComponent()) {
print_r($comp);
}
```
I don't get any errors, but also no output. How can I retreive the events, so that I can save it in a MySQL database.

I also want to sync the events, like for instance every day.

**Comment by iCalcreator** [comment]
Code looks ok, check the return from the parse method, FALSE on error.
Anything tricky with the fb link?

**Comment by JeroenSteen** [comment]
`var_dump($v->parse());` gives me `bool(false)` indeed.
The Facebook link I found on: https://www.facebook.com/events/upcoming?action_history=null
By looking at the url "Upcoming Events" and changed it from `webcal://` to `http://www.facebook.com/ical/u..`. If I go to the url it downloads an ics-file.
