### ISSUE TITLE
Error on Authenticated iCalendar parsing

### ISSUE THREAD

**Issue by josepalos** [iCalcreator/iCalcreator#33]
When trying to parse an URL that needs a context (authentication), the method parse gets the url correctly, but the structure of the if condition leads to a false result because of the last part:
`if( ! empty( $context ) && filter_var( $file, FILTER_VALIDATE_URL ) && ( FALSE === ( $rows = file_get_contents( $file, FALSE, $context ))))`
When the content is correct, the last condition evaluates to false, so the if fails and the code executes the elseif statement (getting the file from the url without authentication).

This can be corrected with a nested if with the last condition.

**Comment by iCalcreator** [comment]
Thanks, included in the coming 2.24 release (mid april)!

**Comment by iCalcreator** [comment]
Ref 2.23.18
