### ISSUE TITLE
Don't append host to UID

### ISSUE THREAD

**Issue by grosch** [iCalcreator/iCalcreator#38]
The RFC spec does not require a host to be appended to the UID.  How do I tell your framework to not do so?  I want *just* the UUID value set there.

**Comment by iCalcreator** [comment]
try

$vevent->setProperty("uid","some_unique_value <20070803T194810CEST-0123U3PXiX@kigkonsult.se>");

**Comment by grosch** [comment]
This is me feeling stupid now :)
