### ISSUE TITLE
PRODID ignored

### ISSUE THREAD

**Issue by grosch** [iCalcreator/iCalcreator#40]
When I call `$vcalendar->setProperty(util::$PRODID, 'some value here');` it's being ignored.  The createCalendar() call is still printing out a line like so:

> PRODID:-//localhost//NONSGML kigkonsult.se iCalcreator 2.23.7//

**Comment by grosch** [comment]
Setting util::$LANGUAGE isn't a good option here because it adds itself in too many places automatically.

Same with util::$UNIQUE_ID

**Comment by iCalcreator** [comment]
Nice to notice you are testing 2.23.7, note, evaluating only, no production use!

Please don't alter PRODID, it would violate the iCalcreator licence.

Right now, prepare 2.23.9, a few bugs fixed.

**Comment by iCalcreator** [comment]
Using the util::$LANGUAGE (etc) as 'keyword' improves robustness..
