### ISSUE TITLE
Duplicate timezones

### ISSUE THREAD

**Issue by grosch** [iCalcreator/iCalcreator#42]
If I call kigkonsult\iCalcreator\timezoneHandler::createTimezone more than once, you're generating that header more than once.  Basic usage is going to be I parse the .ics file, I add a new event, and then I write the file back out.  So if my new event includes a timezone component, I need to call createTimezone....but if the file already had that block, then I've duplicated the VTIMEZONE header.

Please internally ensure that the VTIMEZONE blocks are not duplicated.

**Comment by iCalcreator** [comment]
If you want to call createTimezone more than once
do call
$vcalendar->deleteComponent( 'vtimezone' );
before...

**Comment by grosch** [comment]
If I delete the entire component, then I have to parse the entire file and find all of the timezones being used so that I can then pass all of those into the createTimezone method, right?  Seems like this should be handled internally for me.

**Comment by iCalcreator** [comment]
first, parse the file
make some operations
...
if you then need to (re-)create timezone component,
delete component timezone (if exists)
createTimezone() 
ok?

**Comment by grosch** [comment]
Sorry, I'm probably just missing something, but in looking at the code it seems like the timezone is a required property for the createTimezone() call.  So I parse the file, make a mod, delete the vtimzone component....and then I have to loop through every calendar item and look at every property that might have a TZID set on it, and then call create on the unique ones.

Seems like it would be much better that when I call createTimezone it just internally deletes that one piece from the timezone block and recreates it.

**Comment by grosch** [comment]
Thoughts?
