### ISSUE TITLE
Calendar ignoring config

### ISSUE THREAD

**Issue by grosch** [iCalcreator/iCalcreator#43]
When I use the following code, you're reading from /var/www/api/public/20170428043334.ics (where that filename changes) instead of the /var/www/api/calendars directory, and notice the filename is wrong as well.

        $calendar = new vcalendar();
        $calendar->setConfig([
            util\util::$DIRECTORY => '/var/www/api/calendars',
            util\util::$FILENAME => $team_uid . '.ics'
        ]);
        $calendar->parse();

**Comment by grosch** [comment]
This is with v2.23.12

**Comment by grosch** [comment]
Directory was missing a component :(

**Comment by akkivaghasiya5** [comment]
@grosch I'm facing same issue. Can you explain that how to fix it?

**Comment by grosch** [comment]
In my case the value I specified for DIRECTORY was an incorrect path.  My calendars directory was at /var/www/api/public/calendars.
