### ISSUE TITLE
util.php error

### ISSUE THREAD

**Issue by grosch** [iCalcreator/iCalcreator#44]
In my apache error log I'm seeing this:

> PHP Notice:  Undefined offset: -1 in /var/www/api/vendor/kigkonsult/icalcreator/src/util/util.php on line 918

That's happening from this code.  It seems to be writing the calendar file correctly still.

        $calendar = new vcalendar();
        $calendar->setConfig([
            util\util::$DIRECTORY => '/var/www/api/public/calendars',
            util\util::$FILENAME => $team_uid . '.ics'
        ]);
        error_log($calendar->getConfig(util\util::$DIRECTORY), 0);
        error_log($calendar->getConfig(util\util::$FILENAME), 0);

        $vevent = $calendar->newComponent('vevent');

        $vevent->setProperty(util\util::$DTSTART, ['timestamp' => $event->start, 'tz' => $event->timezone]);
        $vevent->setProperty(util\util::$DTEND, ['timestamp' => $event->end, 'tz' => $event->timezone]);
        $vevent->setProperty(util\util::$SUMMARY, $event->summary);

        if ($event->description !== null) {
            $vevent->setProperty(util\util::$DESCRIPTION, $event->description);
        }

        if ($event->location !== null) {
            $vevent->setProperty(util\util::$LOCATION, $event->location);
        }

        if ($event->url !== null) {
            $vevent->setProperty(util\util::$URL, $event->url);
        }

        if (!empty($event->recurrence_frequency)) {
            $args = [];

            $recurrenceFrequency = trim(strtoupper($event->recurrence_frequency));
            switch ($recurrenceFrequency) {
                case 'DAILY':
                case 'WEEKLY':
                case 'MONTHLY':
                case 'YEARLY':
                    $args[util\util::$FREQ] = $recurrenceFrequency;
                    break;

                default:
                    throw new RestException(412, "Invalid recurrence frequency '$recurrenceFrequency'.");
            }

            if ($event->recurrence_interval > 1) {
                $args[util\util::$INTERVAL] = $event->recurrence_interval;
            }

            if ($event->recurrence_end_date > 0) {
                $date = new \DateTime("@$event->recurrence_end_date");
                $args[util\util::$UNTIL] = $date->format('Ymd\THis\Z');
            } else {
                $args[util\util::$COUNT] = $event->recurrence_count;
            }

            $vevent->setProperty(util\util::$RRULE);
        }

        $vevent->setProperty('X-APPLE-TRAVEL-ADVISORY-BEHAVIOR', 'AUTOMATIC');

        $uid = ...

        $vevent->setProperty('uid', $uid);

        $calendar->sort();
        $calendar->saveCalendar();

**Comment by iCalcreator** [comment]
Right, a bug...
looking into it
Do you have a ical file snippet so I can test it?

**Comment by grosch** [comment]
I'm not seeing it any longer.  I'll let you know if I see it again and attach the file.

**Comment by iCalcreator** [comment]
In any case, it's a bug to be fixed.

**Comment by iCalcreator** [comment]
Ref 2.23.18
