### ISSUE TITLE
Auto-set last modified

### ISSUE THREAD

**Issue by grosch** [iCalcreator/iCalcreator#46]
If I call setComponent on a component that already exists, can you automatically set the last-modified date to the current time?

**Comment by iCalcreator** [comment]
If you call
$vevent->setLastModified()
without arguments, current datestamp is set (or overwrited)

**Comment by grosch** [comment]
Yes, understood.  But I'm asking that you call that internal to the API whenever I update a component, as opposed to our code having to remember to call it any time we make an update.

**Comment by iCalcreator** [comment]
last-modified is not mandatory, it's up to the user to do it if an update is done.

**Comment by grosch** [comment]
OK, I have it in my code.  I just figured it'd be easier if you automatically added it on update.
