### ISSUE TITLE
Delete/modify all future events

### ISSUE THREAD

**Issue by grosch** [iCalcreator/iCalcreator#47]
When doing a modification, can you show how to implement an "All Future" option?  For example, in iCal when I do this it modifies all future calendar items that are part of this series where the individual date has not already been modified.

Same with Delete all Future events please.

**Comment by iCalcreator** [comment]
Sorry, "All Future" option... ??

Example, every other day - forever:
$vevent->setProperty( 'rrule', array( 'FREQ' => "DAILY", 'INTERVAL' => 2 ));

**Comment by grosch** [comment]
So assume I have an existing component that's recurring every day for 14 days.  I now want to tell it that on the 5th day, and all days going forward, that there is a new title, or the time changed, etc...

**Comment by iCalcreator** [comment]
If you alter title, it's another event.
If not, rfc5545 restricts 
'The "RRULE" property SHOULD NOT occur more than once in a component.' 
so you can't use double RRULEs i the same event.
(But I think iCalcreator will manage it)
To be strict, perhaps one RRULE with one RDATE (with multiple dates)?

**Comment by grosch** [comment]
Yes, you're correct.  I'm just looking for an example of how to perform this action with your API.
