### ISSUE TITLE
getComponent() with a UID only returns one item

### ISSUE THREAD

**Issue by grosch** [iCalcreator/iCalcreator#48]
Your format 4 example for getComponent says, "Get (first/next) component with UID as key".  However, it always seems to just return the first component.  If there's a modification to a recurring item, that results in two items in the calendar file with the same UID.   

How do I get at the "other" elements with that same UID?  

Does the API guarantee that it always returns the primary (the ones without a RECURRENCE-ID) component when calling with a UID?

**Comment by iCalcreator** [comment]
getComponent with UID as argument
will only work with a UID containing '@'...

Record a new bug...

**Comment by grosch** [comment]
"Record a new bug..." isn't that what this issues area is?  :)

**Comment by iCalcreator** [comment]
yes, looking into it ;)

**Comment by iCalcreator** [comment]
Ref 2.23.18
