### ISSUE TITLE
getProperty on DTSTART not returning timezone

### ISSUE THREAD

**Issue by grosch** [iCalcreator/iCalcreator#49]
Here's an example:

    <?php
    
    require_once 'iCalcreator.php';
    use kigkonsult\iCalcreator\{vcalendar,util};
    
    $calendar = new vcalendar();
    
    $vevent = $calendar->newComponent('vevent');
    
    $seconds = 1493349979;
    $vevent->setProperty(util\util::$DTSTART, ['timestamp' => $seconds, 'tz' => 'America/Los_Angeles']);
    
    kigkonsult\iCalcreator\timezoneHandler::createTimezone( $calendar, 'America/Los_Angeles', [] );
    
    $event = $calendar->getComponent(util\util::$LCVEVENT);
    echo print_r($event->getProperty(util\util::$DTSTART), true);

And here's the output:

> Array
(
    [year] => 2017
    [month] => 04
    [day] => 28
    [hour] => 03
    [min] => 26
    [sec] => 19
)

**Comment by iCalcreator** [comment]
Using timestamp with tz=offset will result in a local DATE-TIME
but a tz=timezone will be ignored....

**Comment by grosch** [comment]
But that's a bug, because that means I can't get back the proper data.  So I see that the event is at 3:26am, but 3:26 am in which timezone?

**Comment by iCalcreator** [comment]
I'll do some more testing on timestamps...

**Comment by iCalcreator** [comment]
Well, let me conclude how iCalcreator (DTSTART etc) are using timestamps... ;)
timestamp without tz results in UTC date (suffixed by Z)
timestamp with tz=offset, offset updates timestamp and output as local date (without TZID)
timestamp with tz=timezone, date (without suffix Z) and timezone only set as TZID parameter
  (but if timestamp is UTC, date is UTC...)

Works as expected in both 2.22.5 and 2.23.12+

But, you made a typo error, 
echo print_r($event->getProperty(util\util::$DTSTART), true);
outputs the date without any parameters,
correct the code to
echo print_r($event->getProperty(util\util::$DTSTART), false, true);
outputs the date with parameter TZID

Btw, you may use
$convDate = array( 'timestamp' => $seconds ); // $seconds in UTC
kigkonsult\iCalcreator\timezoneHandler::transformDateTime( $convDate, 'UTC', 'America/Los_Angeles' );
$event->setProperty( 'DTSTART', $convDate, array( 'TZID' => 'America/Los_Angeles' ));
to get a DTSTART 'America/Los_Angeles' timezone date.

**Comment by grosch** [comment]
That's really odd.  Passing "false, true" isn't really valid.  false just means to directly send the output, whereas true means to return it.  So if you give false you don't need the echo.  I'll have to check again when I get home tonight what I'm getting back (Don't have php7 at work)

**Comment by grosch** [comment]
> $convDate = array( 'timestamp' => $seconds ); // $seconds in UTC
kigkonsult\iCalcreator\timezoneHandler::transformDateTime( $convDate, 'UTC', 'America/Los_Angeles' );
$event->setProperty( 'DTSTART', $convDate, array( 'TZID' => 'America/Los_Angeles' ));

Awesome, this will make my life much easier!
