### ISSUE TITLE
VALARM not outputting the UID

### ISSUE THREAD

**Issue by grosch** [iCalcreator/iCalcreator#51]
Using the below code I'm not getting the UID field.

        if (!empty($event->alarm)) {
            /** @var valarm $alarm */
            $alarm = $vevent->newComponent(util\util::$LCVALARM);
            $alarm->setProperty(util\util::$TRIGGER, $event->alarm);

            $alarmUid = $this->uuid();
            
            $alarm->setProperty('X-WR-ALARMUID', $alarmUid);
            $alarm->setProperty(util\util::$UID, $alarmUid);
            $alarm->setDescription("Reminder");
            $alarm->setAction("DISPLAY");
        }

I end up with this:

> BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:Reminder
TRIGGER:-PT0H15M0S
X-WR-ALARMUID:a0a86647-b3cc-4831-817a-01e4f1fa25f2
END:VALARM

**Comment by grosch** [comment]
v2.23.16

**Comment by grosch** [comment]
Is this because valarm doesn't have the UIDtrait on it?

**Comment by grosch** [comment]
OK, so I looked closer at the spec and UID is not required on VALARM.  Microsoft Outlook does not include it, whereas Apple's Calendar program does. 

Would there be any harm in allowing it, and only outputting it if the value is indeed set?  As I'm primarily targeting iOS users with these calendars, I think it'd be good to include it since Apple does.

**Comment by iCalcreator** [comment]
The rfc5545 states no UID in ALARM.....
But you may add as many X-properties as you like.
