### ISSUE TITLE
VALARM TRIGGER not validated

### ISSUE THREAD

**Issue by grosch** [iCalcreator/iCalcreator#52]
If I pass in something like "bob" for the TRIGGER of a VALARM, I get back this:

> TRIGGER;VALUE=DATE-TIME:19700101T000000Z

I'd rather get back an exception saying it's the wrong format.

**Comment by iCalcreator** [comment]
One may say setProperty should return false on error input, 
but it's also a matter of how deep validation of input iCalcreator
should do, I'll open up an investigation issue.

As a work-around I recommend validation before string date input like
`if( false === strtotime( $dateString ))
  echo 'date error in input' );
else
...`
