### ISSUE TITLE
iCalvCard.php $fname not defined

### ISSUE THREAD

**Issue by grosch** [iCalcreator/iCalcreator#53]
In 2.23.16 branch, at line 144 of iCalvCard.php you're putting to the $fname variable instead of $fName.  Note the difference in case.

**Comment by grosch** [comment]
I just fixed this in pull request #54 along with a bunch of other items.  I REALLY new to github sharing so be careful :)

**Comment by iCalcreator** [comment]
Ref 2.23.18
