### ISSUE TITLE
Get all components related to UID

### ISSUE THREAD

**Issue by grosch** [iCalcreator/iCalcreator#59]
I'm struggling to figure out how to get everything related to a UID.  If I call getComponent and pass a UID, I get back *one* piece of it.  For example, I expected to get back the main event and then instance that had been modified.  I just get back the main event. 

If I call selectComponents with a UID, then I get back false.

**Comment by grosch** [comment]
For example, here's a recurring item that has one instance of it modified:

> BEGIN:VEVENT
CREATED:20170625T232842Z
UID:565C2273-3F01-4424-A3BB-2CABBB39F26A
RRULE:FREQ=DAILY;COUNT=5
DTEND;TZID=America/Los_Angeles:20180528T010000
TRANSP:OPAQUE
SUMMARY:Repeating
DTSTART;TZID=America/Los_Angeles:20180528T000000
DTSTAMP:20170625T233001Z
X-APPLE-TRAVEL-ADVISORY-BEHAVIOR:AUTOMATIC
SEQUENCE:0
END:VEVENT
BEGIN:VEVENT
CREATED:20170625T232842Z
UID:565C2273-3F01-4424-A3BB-2CABBB39F26A
DTEND;TZID=America/Los_Angeles:20180530T100000
TRANSP:OPAQUE
X-APPLE-TRAVEL-ADVISORY-BEHAVIOR:AUTOMATIC
SUMMARY:Repeating offset
DTSTART;TZID=America/Los_Angeles:20180530T090000
DTSTAMP:20170625T232907Z
SEQUENCE:0
RECURRENCE-ID;TZID=America/Los_Angeles:20180530T000000
END:VEVENT

When I call getComponent I just get back 

> BEGIN:VEVENT
CREATED:20170625T232842Z
UID:565C2273-3F01-4424-A3BB-2CABBB39F26A
RRULE:FREQ=DAILY;COUNT=5
DTEND;TZID=America/Los_Angeles:20180528T010000
TRANSP:OPAQUE
SUMMARY:Repeating
DTSTART;TZID=America/Los_Angeles:20180528T000000
DTSTAMP:20170625T233001Z
X-APPLE-TRAVEL-ADVISORY-BEHAVIOR:AUTOMATIC
SEQUENCE:0
END:VEVENT

I'm not getting back the modified instance:

> BEGIN:VEVENT
CREATED:20170625T232842Z
UID:565C2273-3F01-4424-A3BB-2CABBB39F26A
DTEND;TZID=America/Los_Angeles:20180530T100000
TRANSP:OPAQUE
X-APPLE-TRAVEL-ADVISORY-BEHAVIOR:AUTOMATIC
SUMMARY:Repeating offset
DTSTART;TZID=America/Los_Angeles:20180530T090000
DTSTAMP:20170625T232907Z
SEQUENCE:0
RECURRENCE-ID;TZID=America/Los_Angeles:20180530T000000
END:VEVENT


As they both have the same UID, I'd expect to get back an array of two VEVENT items.

**Comment by iCalcreator** [comment]
The getComponent method returns one component or false.
If you expect more than one, use
`while( $comp = $vcalendar->getComponent()) {`
as noted in the docs.
