### ISSUE TITLE
Make 2.20.x version that is compatible with PHP 7

### ISSUE THREAD

**Issue by lkmorlan** [iCalcreator/iCalcreator#67]
Drupal module Date iCal (date_ical) is not compatible with versions of iCalcreator after 2.20. This version is not compatible with PHP 7. There is already a patch to iCalcreator that makes it compatible with PHP 7:
https://www.drupal.org/project/date_ical/issues/2707373#comment-11574961
I suggest applying this patch and releasing 2.20.3.

**Comment by iCalcreator** [comment]
To solve the issue, upgrade to 2.24.2.
But I recommend to upgrade to 2.26, PSR1+4 fixed.
2.26.x will be released early december, next stable.

**Comment by lkmorlan** [comment]
The developer of the Drupal module Date iCal has said that the amount of work needed to support later versions of iCalcreator is too much. So upgrading is not a feasible solution. Making iCalcreator compatible with PHP 7 is a small change that is feasible.
