### ISSUE TITLE
Register iCalcreator at packagist.org

### ISSUE THREAD

**Issue by kozi** [iCalcreator/iCalcreator#7]
Are you going to register your project at packagist.org?
The composer.json file is only useful if the project is registered at https://packagist.org

**Comment by garyee** [comment]
+1 even if one can make use of the composer.json even if it is not

**Comment by PowerKiKi** [comment]
It is published on packagist: https://packagist.org/packages/kigkonsult/icalcreator

**Comment by dmotd** [comment]
I think this still requires some versioning at packagist. 

```text
# composer require kigkonsult/icalcreator

  [InvalidArgumentException]                                                                                                                              
  Could not find package kigkonsult/icalcreator at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability
```

**Comment by PowerKiKi** [comment]
since there is no release, you need to specifiy master:
`composer require kigkonsult/icalcreator:dev-master`

**Comment by MECU** [comment]
Can you tag a release version please?

**Comment by aaronschmied** [comment]
Can you tag a release version please?

**Comment by iCalcreator** [comment]
Please note the PowerKIKI comment, above.

**Comment by lsolesen** [comment]
It would be great with a tagged version.

**Comment by PowerKiKi** [comment]
If you are unsatisfied with this project, I'd suggest you to have a look at https://github.com/fruux/sabre-vobject. It is a very mature project with the same goals as this one.

**Comment by c33s** [comment]
@PowerKiKi please add a simple tag for your great lib, we are all satisfied with your lib and want to use it. don't send us away using a different lib.
consider adding a "0.1.0" version tag. as your lib is quite stable and don't get that much commits, having a 0.1.0 and increasing this version every now and then would allow us to use your lib as normal dependency.

>Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.
http://semver.org

why this is so important:

if someone use a lib in a project which requires your lib, the missing tag in your lib requires the developer to add both dependencies in his composer file (the lib he wants to use and your lib) or lowering the minimum stability setting in the composer file.

so adding a simple tag now and then really helps development

**Comment by PowerKiKi** [comment]
@c33s, I am just a passerby, I have nothing to do with this project. Please address your concerns to the owner, @iCalcreator.
