### ISSUE TITLE
Namespace change requires manual intervention

### ISSUE THREAD

**Issue by nschilling** [iCalcreator/iCalcreator#70]
I'm not sure if you follow [Semver](https://semver.org/#what-do-i-do-if-i-accidentally-release-a-backwards-incompatible-change-as-a-minor-version), but I think a recent release introduced API breakage.

The upgrade to v2.26 changes the namespace from `kigkonsult\iCalcreator` to `Kigkonsult\Icalcreator` and requires changes in the client code. [Packagist](https://packagist.org/packages/kigkonsult/icalcreator) lists v2.24 and v2.27 but doesn't list v2.26. Maybe that's why the issue didn't surface earlier.

**Comment by iCalcreator** [comment]
Yes, you are right, sorry for the inconvenience but it had to be done.

About Packagist, I don't know why they don't list 2.26.

But I'm quite sure you like the next major 2.28 (i.e. now release candidate 2.27.16)
