### ISSUE TITLE
Usage with PHPMailer

### ISSUE THREAD

**Issue by codingP4nda** [iCalcreator/iCalcreator#73]
I'm currently trying to use the iCalcreator with PHPMailer - since PHPMailer has the Ical property and they refer to you. But I couldn't yet find what exactly I have to pass to that property in order for it to work...? The Ical-property expects a string... 

Thanks for your help!

**Comment by iCalcreator** [comment]
I'm not at all familiar with usage of PHPMailer but, after reviewing PHPMailer
code(-docs) and (property Ical) usage, I think you may set the PHPMailer::Ical
property to the output of (iCalcreator) Vcalendar::createCalendar() method.

You will found a nice PHPMailer and iCal brief overview usage at
<https://stackoverflow.com/questions/21346902/how-to-send-ical-with-phpmailer>
