### ISSUE TITLE
COLOR Property support

### ISSUE THREAD

**Issue by 1tft** [iCalcreator/iCalcreator#74]
Hello,
is it possible that iCalcreator will support setting of color attribute (https://tools.ietf.org/html/rfc7986#page-10), at least for calendar object?
There exists some client software, which already supports that property (I think e.g. CalDav Sync - Android calendar sync client).

Best regards.

**Comment by iCalcreator** [comment]
Now review the rfc 7986...
Plan to implement it in the 2.30 version,
planned later this or early next year.
Otherwise in the coming 2.28 if sponsoring found,
i.e. about 1-2 month.

**Comment by 1tft** [comment]
Hello iCalcreator!
Thank you for your prompt answer. Unfortunately I use iCalcreator for a complete new project. So I have only costs at the moment and no income with this project. Regarding a donation I will contact you soon.
Fortunately color feature is not so important at the moment, because only a few systems support it, not even Google Calendar does support it. So its OK, if you do not prioritise this feature.
Thank you again for you great job and project - Best regards.

**Comment by iCalcreator** [comment]
Will be fixed in 2.30 (prerelease 2.29.x)

**Comment by iCalcreator** [comment]
Fixed in 2.29.14
