### ISSUE TITLE
Hi ICalcreateor

### ISSUE THREAD

**Issue by maggsweb** [iCalcreator/iCalcreator#76]
I'm getting this warning in my logs when using iCalcreator:

    "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?
    /vendor/kigkonsult/icalcreator/src/Vcalendar.php on line 997

The error message is resolved by adding the '2'.
Can I submit a pull-request to modify this?
Thanks

**Comment by iCalcreator** [comment]
Yes, should be "continue 2", thanks. Fix a new release asap!

**Comment by maggsweb** [comment]
Awesome, thanks very much.

**Comment by iCalcreator** [comment]
Removed the switch default and fixed in 2.27.21
