### ISSUE TITLE
RRULE dtstart/dtend always set to initial dates

### ISSUE THREAD

**Issue by dleffler** [iCalcreator/iCalcreator#77]
Perhaps this is a misunderstanding on my part, but using v2.26 or v2.27 on an ics via selectComponents() with default params for flat, any, split returns events with an RRULE containing the 1st date as the dtstart/dtend for all repeated events, though they do appear in the array correctly (year, month, day). EG, the below will return a correct array for all repeats, but the dtstart/dtend will be the same for each entry, that of the initial occurance.

```
BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
PRODID:-//VueSoft//CsvToIcs//EN
X-WR-TIMEZONE:America/New_York
BEGIN:VTIMEZONE
TZID:Eastern Standard Time
BEGIN:STANDARD
DTSTART:20181102T020000
RRULE:FREQ=YEARLY;BYDAY=1SU;BYHOUR=2;BYMINUTE=0;BYMONTH=11
TZNAME:Eastern Standard Time
TZOFFSETFROM:-0400
TZOFFSETTO:-0500
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:20180301T020000
RRULE:FREQ=YEARLY;BYDAY=2SU;BYHOUR=2;BYMINUTE=0;BYMONTH=3
TZNAME:Eastern Daylight Time
TZOFFSETFROM:-0500
TZOFFSETTO:-0400
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
DESCRIPTION:Action Plan: We will offer evangelistic training events to 
 encourage conversion growth.\nLeader -Keith McWhorter
DTEND;VALUE=DATE:20190704
DTSTAMP:20190619T002411Z
DTSTART;VALUE=DATE:20190703
RRULE:FREQ=MONTHLY;INTERVAL=3;BYMONTHDAY=3
SUMMARY:Evangelism Vision Team
UID:788893dd-0c2d-417b-a87a-ce9553af58f0
END:VEVENT
END:VCALENDAR

**Comment by iCalcreator** [comment]
Yes, you are right, they are the same.
But, for each component, look for properties
X-RECURRENCE  (int) number
X-CURRENT-DTSTART  (string) date
X-CURRENT-DTEND  (string) date

Constants
in 2.26, UtilSelect::X_CURRENT_DTSTART etc
in 2.27, Vcalendar::X_CURRENT_DTSTART etc
