### ISSUE TITLE
Action property values does not allow non-standard property parameters

### ISSUE THREAD

**Issue by stas-dovgodko** [iCalcreator/iCalcreator#78]
According to rfc5545 "Property Parameters:  IANA and non-standard property parameters can
      be specified on this property." BUT ACTIONtrait.php throws exception for "none" value for example

**Comment by iCalcreator** [comment]
Looking into it!

**Comment by iCalcreator** [comment]
Do you mean ACTION property PARAMETERs or VALUE ?

As for now you can set (Action) x-prefixed parameters (ex. 'X-KEY')
but the ACTION value are restricted to one of AUDIO, DISPLAY, EMAIL, PROCEDURE.

**Comment by iCalcreator** [comment]
Will be fixed in 2.30 (prerelease 2.29.x)

**Comment by iCalcreator** [comment]
Fixed in 2.29.14
