### ISSUE TITLE
Version numbering is a bit confusing

### ISSUE THREAD

**Issue by jenswegar** [iCalcreator/iCalcreator#81]
The version numbering of this library is a bit confusing to me, should it follow the semver (https://semver.org/) standard or not? You have a release tagged 2.26.9 (released Jul 14th) which has been released _after_ 2.27.21 (released Jun 6th). And in the readme you mention that 2.28.2 is the current stable master, and 2.29.8 is a release candidate for 2.30, however there is no 2.29.8 tag, only a 2.29.14 tag. 

All this makes it very confusing to know which versions are safe to upgrade to, and which might break something. 

I would suggest standardizing the versioning scheme to follow semver more strict so that you don't use patch versions of lower minor versions to indicate release candidates of the next minor version. Instead use -alpha1, beta1, or -RC1 etc as the tags. E.g. to indicate the release candidate for 2.30.0, tag it with 2.30.0-RC1. This way it is clear that if I update from e.g. 2.29.2 to 2.29.8 I should not be pulling in changes from a future 2.30 release that might break some API.

Other than that, thanks for your work on a great library :)

**Comment by iCalcreator** [comment]
Yes, you are right, versioning are tricky.
As a general rule, master versions are safe, tags with higher version number are bugfixes or release candidates as noted in the commit comment.
Thanks for the nice words.
