### ISSUE TITLE
FileName removed in 2.29.4

### ISSUE THREAD

**Issue by MR4online** [iCalcreator/iCalcreator#82]
It seems like the config for a filename in the ics-header has been removed and replaced by a fake-name. 
I dont think this is a good idea, because some implementations look like this:

Calendar-URL to ensure its loaded by all clients:
https://calendar.com/file.ics

so the Filename-Header should be "file.ics" not "fake-foo.ics".

**Comment by iCalcreator** [comment]
In the the 2.29.14 Vcalendar::returnCalendar() method (i.e. HttpFactory::returnCalendar)?
Yes, you are right, 
will add to the fix-list, 
add a new method argument (fileName),
new release asap,
OK?

**Comment by iCalcreator** [comment]
Fixed in 2.29.15

**Comment by MR4online** [comment]
thx!
