### ISSUE TITLE
Please use DateTimeInterface as type hint

### ISSUE THREAD

**Issue by Ugoku** [iCalcreator/iCalcreator#83]
Right now, when you try to use a `DateTimeImmutable` for a function that accepts a `DateTime`, Phpstan will complain. For example, the function `setDtstart` in `src/Traits/DUEtrait.php`.

 If you use `DateTimeInterface` instead, both `DateTime` and `DateTimeImmutable` will be accepted.

**Comment by iCalcreator** [comment]
Fixed in 2.29.18, methods with DateTime arg now accepts DateTimeInterface

**Comment by Ugoku** [comment]
Great, thanks!
