### ISSUE TITLE
PHP 7.4 compatibility

### ISSUE THREAD

**Issue by Ugoku** [iCalcreator/iCalcreator#84]
PHP 7.4 [deprecated curly brace syntax](https://www.php.net/manual/en/migration74.deprecated.php) for array and string offsets.

This appears in `Kigkonsult\Icalcreator\Util\DateIntervalFactory`: `return (( 3 <= strlen( $value )) && ( in_array( $value{0}, $PREFIXARR )));`, `Kigkonsult\Icalcreator\Util\\StringFactory`: `in_array( $rows[$i1]{0}, $CHARs )) {` and possibly other places.

I am willing to submit a PR for this

**Comment by iCalcreator** [comment]
Include it in the next bug-fix release, coming asap

**Comment by iCalcreator** [comment]
Fixed in 2.29.21, please test, ok?
