### ISSUE TITLE
Issue with Monthly Recurrence on Day of Week

### ISSUE THREAD

**Issue by neotsn** [iCalcreator/iCalcreator#87]
**Version:** v2.29.21

When creating a calendar with Monthly recurrence, there are two options available: 
- By Day of Month (e.g. Christmas Dec 24-25)
- By Day of Week (e.g. US Thanksgiving, Every 4th Thursday of November)

I then couple this with no termination date in the ICS (though in the database it is implied as the End of Epoch for int32 values in 2038). For the calendar I am displaying, I have a need to figure out the Final End Date of any ICS string, and to do this we use the approach below in a method of a wrapper class to handle Icalcreator functionality without needing to invoke its methods in the codebase at large...

```php
try {
    // start at 2038 and work backwards
    $year = 2038;
    $events = [];

    while (!$events && $year >= 1970) {
        $events = ($year == 2038)
            // Only look within the range of the year that the END-OF-EPOCH handles completely (epoc ends Jan 19, 2038 @ 03:14:07 UTC), so 1/1 - 1/18
            ? $this->vCalendar->selectComponents($year, 1, 1, $year, 1, 18, Vcalendar::VEVENT, false, true)
            // gets all of the events for the given year - returns false when nothing is found
            : $this->vCalendar->selectComponents($year, 1, 1, $year, 12, 31, Vcalendar::VEVENT, false, true);

        error_log($year . ': ' . ($events ? count($events) : 0));
        $year--;
    }

    // find the final occurrence
    $months = end($events);
    $days = end($months);
    $occurrences = end($days);
    $finalOccurrence = end($occurrences);
    error_log(json_encode($finalOccurrence->getXprop(Vcalendar::X_CURRENT_DTEND)));
    $result = new DateTime($finalOccurrence->getXprop(Vcalendar::X_CURRENT_DTEND)[1]);
} catch (Exception $e) {
    error_log($e->getMessage() . ' [VJ34I8]');
}
```
where `$this->vCalendar` is setup with an event already configured and its recurrence rules applied. 

When we run this loop over the Christmas Event, we correctly calculate the Final End Date as `2145419940` or `Friday, December 25, 2037 11:59:00 PM GMT-06:00` marking the end of the holiday.

When we run this loop over the Thanksgiving Event, only the first instance of the event is returned as the Final End Date `1606415400` or `Thursday, November 26, 2020 12:30:00 PM GMT-06:00` marking the correct arbitrary hour I set for the event, but not the correct final end date of some day in 2037.

Using the `$this->vCalendar->createCalendar()` output on the Christmas event, we are given this ICS string (newlines removed):
```ics
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//MyApp//NONSGML kigkonsult.se iCalcreator 2.29.21//
CALSCALE:GREGORIAN
METHOD:PUBLISH
UID:7ddfd606-ba60-46f6-b916-e9c9bf395910
X-WR-CALNAME:Calendar
X-WR-CALDESC:Calendar Description
X-WR-TIMEZONE:America/Chicago
BEGIN:VEVENT
UID:5f36bb8be20b4deb0c06fae7
DTSTAMP:20200814T162755Z
DESCRIPTION:Eventing over Christmas Day
DTSTART;TZID=America/Chicago:20201224T000000
DTEND;TZID=America/Chicago:20201225T235900
RRULE:FREQ=MONTHLY;INTERVAL=12;BYMONTHDAY=24;WKST=SU
SUMMARY:Christmas Event
END:VEVENT
END:VCALENDAR
```
Using the same method for the Thanksgiving Event, we are given this ICS string:
```ics
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//MyApp//NONSGML kigkonsult.se iCalcreator 2.29.21//
CALSCALE:GREGORIAN
METHOD:PUBLISH
UID:ac475a11-8f5a-4a61-b0a4-de357c3cf21b
X-WR-CALNAME:Calendar
X-WR-CALDESC:Calendar Description
X-WR-TIMEZONE:America/Chicago
BEGIN:VEVENT
UID:5f36bc3ae20b4d721108816c
DTSTAMP:20200814T163050Z
DESCRIPTION:Testing event on the 4th Thursday of every November
DTSTART;TZID=America/Chicago:20201126T113000
DTEND;TZID=America/Chicago:20201126T123000
RRULE:FREQ=MONTHLY;INTERVAL=12;BYDAY=TH;BYSETPOS=4;WKS
 T=SU
SUMMARY:Thanksgiving event
END:VEVENT
END:VCALENDAR
```

If I take both of these ICS outputs, and drop them into a Text Editor, saving as a `.ics` file, and then open in a calendar app (say macOS Calendar) they correctly render the recurrences into the next year (2021). However, the output from `selectComponents` is where is inconsistent as it does not correctly handle the "Day of Week (e.g. 4th Thursday of the Month)"  recurrence. And when the error log is viewed, you end up with results that match this output...

```
2038: 0
2037: 0
2036: 0
2035: 0
2034: 0
2033: 0
2032: 0
2031: 0
2030: 0
2029: 0
2028: 0
2027: 0
2026: 0
2025: 0
2024: 0
2023: 0
2022: 0
2021: 0
2020: 1
["X-CURRENT-DTEND","2020-11-26 13:56:00 America\\/Chicago"]
```

I hope that either this is enough information for a fix, or enough information to describe that there is something simple I am missing to get this part working.

**Comment by iCalcreator** [comment]
Working on it but a very tricky combination of recur params.

Workaround ( and simpler) :
RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=TH;BYSETPOS=4;WKST=SU
and result is ok!

**Comment by neotsn** [comment]
Thank you for the work around, I will see how I can swap in this as a replacement.

**Comment by neotsn** [comment]
Unfortunately that is not a sufficient work-around for the primary use-case for Monthly "BYDAY". Consider also Microsoft's Patch Tuesday, which is the first Tuesday of every month. This too fails to render anything past the first date.

This being the case, I'll await the fix in a future release.
Thank you for your work!

**Comment by iCalcreator** [comment]
Testing the new release now, public prel. this weekend.

**Comment by iCalcreator** [comment]
Please test the new release v2.29.25

**Comment by neotsn** [comment]
Downloading, and testing today.

**Comment by neotsn** [comment]
No... while the Final End Date seems to be calculated correctly (thank you), other things are broken now.

It seems that the `\Kigkonsult\Icalcreator\Traits\RRULEtrait::getRrule()` method now returns an associative array in the `BYDAY` field instead of a simple array of weekday abbreviations.

It happens in the `\Kigkonsult\Icalcreator\Traits\RRULEtrait::setRrule()` method...

```php
    /**
     * Set calendar component property rrule
     *
     * @param array   $rruleset
     * @param array   $params
     * @return static
     * @throws InvalidArgumentException
     * @throws Exception
     * @since 2.29.6 2019-06-23
     */
    public function setRrule( $rruleset = null, $params = [] )
    {
        if( empty( $rruleset )) {
            $this->assertEmptyValue( $rruleset, self::RRULE );
            $rruleset = Util::$SP0;
            $params   = [];
        }
        $this->rrule = RecurFactory::setRexrule(
            $rruleset,
            array_merge( (array) $params, $this->getDtstartParams())
        );
        error_log('rruleSet: '. json_encode($rruleset));
        error_log('rruleProp: '. json_encode($this->rrule));
        return $this;
    }
```

Resulting in these values:
```
[Tue Sep 08 15:55:42.355055 2020] rruleSet: {"BYSETPOS":"2","BYDAY":["TU"],"FREQ":"MONTHLY","INTERVAL":"1","WKST":"SU"}
[Tue Sep 08 15:55:42.355089 2020] rruleProp: {"value":{"FREQ":"MONTHLY","INTERVAL":"1","BYDAY":{"DAY":"TU"},"BYSETPOS":"2","WKST":"SU"},"params":[]}
```

This seems to have been added in a couple in `\Kigkonsult\Icalcreator\Util\RecurFactory::orderRRuleBydayKey()`. In this method, what was [a proper if-elseif-else](https://github.com/iCalcreator/iCalcreator/compare/v2.29.21...v2.29.25#diff-f5a38467743e7089ba051cd12bc5ecc1L426) ...

```php
    if( 0 == strcasecmp( Vcalendar::DAY, $BYDAYx )) {
        $output[Vcalendar::BYDAY][Vcalendar::DAY] = strtoupper( $BYDAYv );
    }
    elseif( ! is_array( $BYDAYv )) {
        $output[Vcalendar::BYDAY][$BYDAYx] = $BYDAYv;
    }
    else {
        // ... Another version, but in a loop
    }
```

was replaced with a switch-true case statement, that actually introduces breaking-changes in output, such that a single weekday array now comes back as an associative array with a key, instead of being a numerically keyed array as before.

```php
    case (( 0 == strcasecmp( Vcalendar::DAY, $BYDAYx )) ||
        is_string( $BYDAYv )) :
        $output[Vcalendar::BYDAY][Vcalendar::DAY] =
            strtoupper( $BYDAYv );
        break;
```

When I try to create an event that has WEEKLY frequency on several days of the week, my days are now overwritten with the DAY key, taking only the last value.

```
[Tue Sep 08 16:38:10.782993 2020] rruleSet: {"BYDAY":["TU","WE","TH"],"FREQ":"WEEKLY","INTERVAL":"1","WKST":"SU"}
[Tue Sep 08 16:38:10.783030 2020] rruleProp: {"value":{"FREQ":"WEEKLY","INTERVAL":"1","BYDAY":{"DAY":"TH"},"WKST":"SU"},"params":[]}
```

Please restore the original method that creates a numerically indexed array as originally described in v2.29.21. More testing will be required after this change to ensure nothing else is broken.

**Comment by iCalcreator** [comment]
Thanks, looking into it, asap!

**Comment by iCalcreator** [comment]
Now accepts more RRULE BYDAY formats, please try 2.29.29

**Comment by neotsn** [comment]
Thanks, I will check it out today

**Comment by neotsn** [comment]
Scenarios I have tested:
- ✅ Run-Once Event
- ❌ "Daily restart around Midnight Central" - Final End Date edge case
- ✅ "Lunch Time at work" Event (weekdays 12:00-13:00)
- ✅ "World of Warcraft Patch Tuesday" (weekly on Tuesday)
- ✅ "Bi-weekly Payday" (every 2 weeks on Friday)
- ✅ "Rent Due on the 1st" (Date of Month, consistent)
- ✅ "31st Day of Month" (Date of Month, inconsistent)
- ✅ "Microsoft Patch Tuesday" (1st Tuesday each month)

In testing all the scenarios I have, there seems to be an edge case where when the event is sufficiently frequent (e.g. Daily) or starts sufficiently close to the end of the EPOC timestamp (i.e. `2147483647` or `20380119T031407Z`), the Final End Date that is calculated causes an int32 overflow. For example...

```ics
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//MyApp//NONSGML kigkonsult.se iCalcreator 2.29.29//
CALSCALE:GREGORIAN
METHOD:PUBLISH
UID:794fa3e0-d284-4a4f-b7af-25a212132975
X-WR-CALNAME:Maintenance Window Calendar
X-WR-CALDESC:Maintenance Window of scheduled events affecting services.
X-WR-TIMEZONE:America/Chicago
BEGIN:VEVENT
UID:5f5f97a2e20b4de146325ee9
DTSTAMP:20200914T161738Z
DESCRIPTION:v2.29.29
DTSTART;TZID=America/Chicago:20200914T231600
DTEND;TZID=America/Chicago:20200914T235800
RRULE:FREQ=DAILY;INTERVAL=1;WKST=SU
SUMMARY:Restart every night
END:VEVENT
END:VCALENDAR
```

When I tried creating an event representing a "Restart near midnight" scenario, the Final End Date calculated came back negative: `-2147473816`. So while it is the case that the fixes done in 2.29.25 for the Final End Date calculations actually make it to the end of the EPOC, some of the occurrences which _end_ past the EPOCH are not sufficiently excluded.

This is currently the only remaining issue I have found.

**Comment by iCalcreator** [comment]
Nice set of tests, like to share, OTL?

But, I can't reproduce the error one, works ok for me,
how do you test it?

**Comment by neotsn** [comment]
Unfortunately those were manual tests (using the edit form of the application). I have not figured out yet how far into the code logic I want to begin the unit tests, since I have written a wrapper to encapsulate several method calls to this plugin as a single method call for my application.

Once I have some tests that I think you may be able to use, I can pass them along in a gist. I will double-check my work for the edge case again, and see if I can give you something more reproducible. The edge case happened several times for me while I was going through the tests the other day.

**Comment by neotsn** [comment]
For someone else coming across this issue as an answer to the EPOCH Final End Date requirement, here is how I've modified the implementation, relative to the method posted originally in this thread.

```php
    /**
     * @return bool|\DateTime
     */
    public function getFinalEndDate()
    {
        $result = false;
        try {

            // start at 2038 and work backwards
            $year = 2038;

            // Start on this day, but allow the loop to roll it backward 1 from the start date day if the end date is past the epoch
            $epochEndDay = 18;

            while (!$result && $year >= 1970) {

                $events = ($year == 2038)
                    // Only look within the range of the year that the END-OF-EPOCH handles completely (epoc ends Jan 19, 2038 @ 03:14:07 UTC), so 1/1 - 1/18
                    ? $this->vCalendar->selectComponents($year, 1, 1, $year, 1, $epochEndDay, Vcalendar::VEVENT, false, true)
                    // gets all of the events for the given year - returns false when nothing is found
                    : $this->vCalendar->selectComponents($year, 1, 1, $year, 12, 31, Vcalendar::VEVENT, false, true);

                if ($events) {
                    // find the final occurrence by jumping to the end element of each of the nested arrays.
                    $months = end($events);
                    $days = end($months);
                    $occurrences = end($days);
                    $possibleOccurrence = end($occurrences);

                    $possibleEndDateTime = new DateTime($possibleOccurrence->getXprop(Vcalendar::X_CURRENT_DTEND)[1]);

                    if ($possibleEndDateTime->getTimestamp() <= self::EPOCH_END_UNIX) {
                        $result = clone $possibleEndDateTime;
                    } else {
                        $possibleStartDateTime = new DateTime($possibleOccurrence->getXprop(Vcalendar::X_CURRENT_DTSTART)[1]);
                        // Roll the end date back one day from the start date
                        $epochEndDay = (int)$possibleStartDateTime->format('d') - 1;
                        // Make sure it doesn't go below 1
                        $epochEndDay = ($epochEndDay <= 1) ? 1 : $epochEndDay;
                    }
                } else {
                    $year--;
                }
            }

        } catch (Exception $e) {
            Log::error($e->getMessage() . ' [VJ34I8]', false);
            Log::errorMessage('Could not calculate the final end date. [VJ34I8]');
        }

        return $result;
    }
```

In this way I don't have to recursively traverse (in reverse) the element arrays to find the last suitable element in each of the nested ones. I just adjust the parameters if it ended past the epoch and re-query.

(Developer note: I don't know if the clone of the `$possibleendDateTime` is necessary. Probably not.)
