### ISSUE TITLE
Array-style access of non-arrays in PHP 7.4 

### ISSUE THREAD

**Issue by aamasri** [iCalcreator/iCalcreator#88]
**In file:** /icalcreator/src/Util/DateTimeFactory.php (v2.29.21)
**At line 103:**  if(( $AT == $dateTimeString[0]

PHP **7.4** now throws a notice error which results in failure to create a working iCal string.

The best way to get the first character in $dateTimeString is: substr($dateTimeString, 0, 1)

Please change line 103 to:  if(( $AT === substr($dateTimeString, 0, 1)) && ...

**Comment by aamasri** [comment]
Let me know if you prefer a PR

**Comment by aamasri** [comment]
Thank you 👍

**Comment by iCalcreator** [comment]
Please test the new release v2.29.25

**Comment by aamasri** [comment]
> Please test the new release v2.29.25

👌  Confirmed working in PHP v7.4.8

**Comment by iCalcreator** [comment]
Nice, thanks !
