### ISSUE TITLE
Recent tags are not on a branch

### ISSUE THREAD

**Issue by lkmorlan** [iCalcreator/iCalcreator#90]
Tags made in this repository since v2.28.2 are not in a branch. These tags should be merged into the master branch. This can probably be done by just merging the most recent tag.

**Comment by iCalcreator** [comment]
Major release iCalcreator 2.30 !!

**Comment by Ugoku** [comment]
What changed in 2.30 ? There appears to be no changelog whatsoever, and no message in the tag. [Comparing the source](https://github.com/iCalcreator/iCalcreator/compare/v2.29.30...v2.30.1) is frustrating, because there are a bunch of copyright and version updates.

**Comment by iCalcreator** [comment]
None, the major 2.30 is same as minor (tag) 2.29.30b.

**Comment by lkmorlan** [comment]
Tag v2.30.1 is one commit ahead of branch master.
