### ISSUE TITLE
Google Calendar issue - 1 Character is missing in output

### ISSUE THREAD

**Issue by belt-media** [iCalcreator/iCalcreator#93]
The Last Line is getting cropped so that the last character is missing:

Instead of `END:VCALENDAR` only `END:VCALENDA` is standing in the last row.
Most of the calendar programs don't care e.g. Outlook, Thunderbird but Google Calendar has a big problem.

https://github.com/iCalcreator/iCalcreator/blob/722e161d1a25c3ceec1692642d64a7f2cf5faee9/src/Util/HttpFactory.php#L119

**Comment by iCalcreator** [comment]
Unable to reproduce when extending tests...
Have you altered the (default) eol-chars ("\r\n")?
Are you using any arguments when invoking 'returnCalendar', gzip, cdType, fileName?
What OS are you running on?

**Comment by belt-media** [comment]
I am running a Ubuntu 18.04.5 LTS Server with PHP v7.4.21

And this is the part of the code:

```
<?php 
use Kigkonsult\Icalcreator\Vcalendar;
$this_timezone = "UTC";
$tz = new DateTimezone($this_timezone);
    
$config = array( "unique_id" => tidyFilename($company['name'] ." - ". $fname) );  // set Your unique id
    $v = new vcalendar( $config );                              // create a new calendar instance

    $v->setMethod( Vcalendar::PUBLISH ); // required of some calendar software
    $v->setXprop( Vcalendar::X_WR_CALNAME, tidyFilename($calOutputName)); // required of some calendar software
    $v->setXprop( Vcalendar::X_WR_CALDESC, "my-venue - " . $company['name']); // required of some calendar software
    $v->setXprop( Vcalendar::X_WR_TIMEZONE, $this_timezone); // required of some calendar software

    // Events export
    foreach ($data as $key => $row)
    {
      $firstlayer = (!empty($row['firstlayer']))? $row['firstlayer'] : "";
      $title      = $row['title']." - ".$firstlayer;
      $text       = sprintf("Gebuchte Ressourcen: %s", $firstlayer);
      $dt_from = new DateTime(date_format(date_create($row['start']), 'c'));
      $dt_to   = new DateTime(date_format(date_create($row['end']), 'c'));
      date_timezone_set($dt_from, $tz);
      date_timezone_set($dt_to,   $tz);
      
      
      $text = (strlen($text)<=0)? $title : $text;
      $v->newVevent()               // create an event calendar component    
        ->setDtstart($dt_from)
        ->setDtend($dt_to)
        ->setSummary($title)
        ->setDescription($text);
        
      continue;
    }
    
    $v->vtimezonePopulate()->returnCalendar(false, false, false, $fname);
```

You can call the file with that URL: 
https://eins.my-venue.at/api/v1/d0b2ec7f127b5530040834e25745d90c/ress/kalender.ics

**Comment by belt-media** [comment]
Okay.. 
I found out, that the problem comes from a completely other side of the code.
**One of the included files was not 100% UTF-8 Encoded**, and that ended up in something that disabled Google Calendar to parse my ICAL File.
Sry for that.
