### ISSUE TITLE
Issue with extending classes

### ISSUE THREAD

**Issue by GreTimotej** [iCalcreator/iCalcreator#97]
Hello!

I started using iCalcreator for determing wether the multiple events happen in one day. I tried changing the *Vcalendar.php* where the calendar is created. I have stumbled upon an issue where extendting the IcalBase class is impossible. I tried doing the `composer require kigkonsult/icalcreator` and made sure to edit the composer.json.

When I try to run the script I still get the issue pasted bellow.

If anyone knows what could go wrong here, the help would be much apprechiated.

`PHP Fatal error:  Uncaught Error: Class "Kigkonsult\Icalcreator\IcalBase" not found in C:\projects\icalMerger\vendor\kigkonsult\icalcreator\src\Vcalendar.php:74
Stack trace:
#0 {main}
  thrown in C:\projects\icalMerger\vendor\kigkonsult\icalcreator\src\Vcalendar.php on line 74`

EDIT: I am using PHPv8

**Comment by iCalcreator** [comment]
Please check the autoloader usage?

**Comment by Rajat1192** [comment]
You can change the folder name "kigkonsult" to "Kigkonsult". And can solve the issue.

**Comment by GreTimotej** [comment]
Hello! I think the issue can be closed. I downgraded from PHPv8 to PHPv7 and everything was working well.
Thanks for help @iCalcreator and @Rajat1192.
